num1 = int(input("Enter a number: "))
num2 = int(input("Enter another number: "))
#print("The sum of {} and {} is {}.".format(num1, num2, num1 + num2))
print("The sum of ",num1," and ",num2," is: ",num1+num2)
print("The product of ",num1," and ",num2," is: ",num1 * num2)
print("The quotient of ",num1," and ",num2," is: ",num1 / num2)
print("The difference of ",num1," and ",num2," is: ",num1 - num2)